### PR TITLE
Topic/complete menu structure with new email address

### PR DESCRIPTION
**Pull request by purewasa**
Hi,

three month ago I came across some news about RasPad 3 tablet. I was interested
right away from the start. But before buying one, I wanted to make sure, that
the addon software, that turns a raspbian buster into RasPad OS, would also run
on the upcoming version of raspbian (bullseye). So I downloaded the first
stable but unreleased version of raspbian bullseye for my Raspberry Pi 4 and
tried to install all additional RasPad OS software (raspad-launcher,
raspad-auto-rotator, evdev-right-click-emulation and the onboard keyboard).

After a few modifications the software worked as far as I could test it without
a RasPad 3. (Missing touchscreen and acceleration sensor made
evdev-right-click-emulation and raspad-auto-rotator stop with error, but did not
crash.)

I was at once enthused by the idea of raspad-launcher to have a start menu for
a touchscreen with big icons and I liked the look of the menu a lot. But as soon
as I tried to start my self-written .desktop files, I got aware of the
shortcomings of that program in version 1.8/1.9.1, since my own applications could not
be started! However, I wanted this software to run in my personal environment.
So I decided to contribute to this open source project.

After I managed to compile my own copy of raspad-launcher, I started to
eliminate the shortcomings bit by bit. I only changed the backend part of the
program, leaving the visual appearance as it was.

I fixed the translation and added a German translation file. I completely
reworked the launching of applications, so that it is now compatible with
raspbian's start menu. I fixed the missing icons, completed the menu structure
and made the program start half a second faster. I put all my changes into
one branch and partitioned it into subbranches that each cover one of the above
changes.

For not overwhelming you with all of my commits, I herewith begin this pull
request with the first subbranch topic/complete-menu-structure.
Nevertheless, I invite you to also take a look at the full branch
topic/adaptions-purewasa
( https://github.com/purewasa/raspad-launcher/commits/topic/adaptions-purewasa )

This is my first bigger contribution to an open source project. So I will be
happy, if you like my work and take it on.

Feedback is highly appreciated!

Note: This pull request is identical to my first pull request in respect of the source
code, but now has a real email address in the commits.

### CODE REVIEW

**Comment by sunfounder** [comment]
Hi @purewasa ! We are appreciate your effort!

We have test your commits under the latest bullseye rpios with desktop(no recommended software). And there's seems to be a little problem. adding raspi-ui-overide makes some "ghost" applications. It shows some applications whit not even installed.

We can't merge it if this is not fix. Maybe we can remove the raspi-ui-overider right now?

Thanks again

**Comment by purewasa** [comment]
Hi sunfounder,

thank you for looking at my changes.

Yes, you are right. There are some icons with uninstalled programs (like duplicate "Text Editor" with leafpad). This gets fixed in commit "Add TryExec key handling" ( https://github.com/purewasa/raspad-launcher/commit/f2c73c86c31f06b40a030615f9c238153a2e704e ).

When I programmed the changes to raspad-launcher, I only had a single branch in mind (topic/adaptions-purewasa).
The order of commits were only loosely planned, as I had to find into the project, especially in the first 10 to 20 commits. 
At the end I noticed, that one branch would be too many commits to submit. So, I wanted to break it down into smaller pieces. I reordered the commits by rebasing in a way, that I could subdivide the branch into sections of the main changes. I finally labeled the sections with branch names, emphasizing the main changes.

I could not fully arrange the best order, because the rebase conflicts got to expensive to fix. That is, why the branch of this pull request seems to be kind of incomplete. I did not think of, that this could be a problem. So, I am sorry for this inconvenience!

Your suggestion, to remove the raspi-ui-overrides folder at this point, is possible. But it requires rebasing, which brakes the pull request and invalidates the sense of the branch name. The section of the branch would not be strong enough anymore, to justify an extra branch!

So, my suggestion is, that you take a look at the branch topic/rework-launching-application
( https://github.com/purewasa/raspad-launcher/tree/topic/rework-launching-application ).
This branch is the first, that cointains the fix and it brings a big value to the project.
It provides:
- parsing the Exec key of desktop files, fully compatible with raspbian system menu, to run any desktop file
- Allowing applications, that are run in a terminal, like htop.
- Commands, entered on run page, are parsed like in a shell, with quoting and escape sequences.

If you feel comfortable with this branch, I could create a new PR with it and close this PR.

I am looking forward to hearing from you.

**Comment by sunfounder** [comment]
No problem. @purewasa. Thank you for you effort. we will test it out.

**Comment by sunfounder** [comment]
@purewasa We have test it, branch topic/rework-launching-application works great! Just one little thing though, seem the dialog module need qtquick-control 1.2, so it need to install it on user side. Make sure to add it in to install file, when you make the new PR.

And thanks again!

**Comment by purewasa** [comment]
@sunfounder I am glad your satisfied with my changes!
Thank you for pointing out that package qml-module-qtquick-controls has to be installed. I could not notice it, because that package had been autoinstalled by qt5-quick-demos, which I had installed sometime before.
I will do the change to the install script and submit the new PR.

**Comment by purewasa** [comment]
@sunfounder, I added the QtQuick.Controls 1.2 to the install script. and will now submit a new PR with the branch topic/rework-launching-application.
I close this PR, as it does not fulfill your expectations and I don't want to alter it.

**Pull request closed without merging**
